### PR TITLE
Dont print out 10 tlds at risk of running into encoding errors

### PR DESCRIPTION
**Pull request by arski**
@john-kurkowski @hangtwenty here we go :)

### CODE REVIEW

**Comment by hangtwenty** [comment]
Great thank you!

**Comment by arski** [comment]
sweet! What's your policy on new pip releases? I imagine this is not enough to warrant one (though at the same time if someone runs into the bug it's kind of a deal breaker).

**Comment by hangtwenty** [comment]
@john-kurkowski ?

**Comment by john-kurkowski** [comment]
The policy is: on demand! :smile: Included in 1.7.4.

**Comment by arski** [comment]
I like that policy - thanks a lot! :)

**Pull request merged**
