### PR TITLE
Catch permission error when making cache dir, as well as cache file

### LINKED ISSUE #209: 3.0 creates permission error on .suffix_cache
We had a python dependency on a package that had a dependency on tldextract > 2.0.  Our build pipeline has been pulling in tldextract 2.3, but today it pulled in 3.0 and we started getting this exception in our environment:

File "/usr/local/lib/python3.7/site-packages/tldextract/cache.py", line 104, in run_and_cache
cache_filepath = self._key_to_cachefile_path(namespace, key_args)
File "/usr/local/lib/python3.7/site-packages/tldextract/cache.py", line 95, in _key_to_cachefile_path
_make_dir(cache_path)
File "/usr/local/lib/python3.7/site-packages/tldextract/cache.py", line 155, in _make_dir
os.makedirs(os.path.dirname(filename))
File "/usr/local/lib/python3.7/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/site-packages/tldextract/.suffix_cache'

### PR DESCRIPTION
**Pull request by john-kurkowski**
Stanches #209.

* Move makedir side-effect from string building helper function into try block
* Duplicate warning from writing a single cache file
* Log this at most once per app
* Remove unused vars

### CODE REVIEW

**Comment by john-kurkowski** [comment]
FYI @brycedrennan

**Comment by brycedrennan** [comment]
Ah I hadn't noticed #209 . So it seems some installations have permission to create a file but not a directory. interesting.   I wonder if we should just use a system temp folder instead.  

I'll look more in depth at this tomorrow.

**Comment by john-kurkowski** [comment]
I think it's that creating the directory wasn't wrapped in a `try`. Everything else was. Not about the way user systems distinguish files vs. directories.

System temp folders have been suggested several times in the issue tracker. I was opposed, because I don't want the suffix list to be temporary, evicted at any time by the OS. Maybe I should soften my stance.

My favorite suggestion [is to switch to an XDG standard location](https://github.com/john-kurkowski/tldextract/issues/196#issuecomment-668974052).

**Comment by john-kurkowski** [comment]
Stanches #209 for now. Let's keep that one open for a longer term fix.

**Comment by brycedrennan** [comment]
Sounds good

**Pull request merged**
